EstrelaLivre/EstrelaLivre.Web/Controllers/AdminController.cs
using EstrelaLivre.Dados.Contexto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using EstrelaLivre.Entidades.ViewModels;
using System.Net;
using System.Threading.Tasks;
using EstrelaLivre.Entidades.Modelos;
using System.IO;
using System.Drawing;
using System.Globalization;

namespace EstrelaLivre.Web.Controllers
{
    public class AdminController : Controller
    {
        private ContextoDados db = new ContextoDados();
        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult getProdImageById(int id)
        {
            var imagem = db.Produto.Find(id).Imagem;

            return File(imagem, "image/png");
        }

        public ActionResult getOpicImageById(int id)
        {
            var imagem = db.Opcional.Find(id).Imagem;

            return File(imagem, "image/png");
        }

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        //GET: Gerenciar Administradores
        public ActionResult GerenciarAdministradores()
        {
            var userRoles = new List<RolesViewModel>();

            foreach (var user in UserManager.Users)
            {
                var userRole = new RolesViewModel()
                {
                    UserName = user.UserName,
                    UserID = user.Id,
                    RoleName = string.Join("", UserManager.GetRoles(user.Id))
                };
                
                userRoles.Add(userRole);
            }
            return View(userRoles);
        }

        //POST: Gerenciar Administradores
        [HttpPost]
        public ActionResult GerenciarAdministradores(string UserId, string UserRole)
        {
            if (UserId == null)
            {
                return View("Error");
            }

            UserManager.RemoveFromRole(UserId, UserRole);

            if (UserRole == "Administrador")
            {
                UserManager.AddToRole(UserId, "Usuario");
            }
            else
            {
                UserManager.AddToRole(UserId, "Administrador");
            }

            var userRoles = new List<RolesViewModel>();

            foreach (var user in UserManager.Users)
            {
                var userRole = new RolesViewModel()
                {
                    UserName = user.UserName,
                    UserID = user.Id,
                    RoleName = string.Join("", UserManager.GetRoles(user.Id))
                };

                userRoles.Add(userRole);
            }

            return View(userRoles);
        }

        //GET: Cadastrar Produto
        public ActionResult CadastrarProduto()
        {
            ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoId", "Descricao");
            return View();
        }

        //POST: Cadastrar Produto
        [HttpPost]
        public ActionResult CadastrarProduto([Bind(Include = "Nome,TipoAlimentoID,Quantidade,UnidadeMedida,ImgFile")] ProdutoViewModel model)
        {
            if (ModelState.IsValid)
            {
                Produto novo_produto = new Produto(model);
                byte[] imagem_binaria;

                if (model.ImgFile != null)
                {
                    try
                    {
                        Stream arquivoStream = model.ImgFile.InputStream;
                        imagem_binaria = new byte[arquivoStream.Length];
                        arquivoStream.Read(imagem_binaria, 0, imagem_binaria.Length);
                        
                        if (imagem_binaria != null)
                        {
                            novo_produto.Imagem = imagem_binaria;
                        }
                        else
                        {
                            ViewBag.Message = "Falha na leitura da imagem";
                            ViewBag.Status = "FAIL";
                            ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoId", "Descricao");
                            return View();
                        }

                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = " Erro " + ex.Message;
                        ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoId", "Descricao");
                        return View();
                    }
                }

                else
                {
                    novo_produto.Imagem = null;
                }

                db.Produto.Add(novo_produto);
                db.SaveChanges();
                
            }
            else
            {
                ViewBag.Error = true;
            }

            if (ViewBag.Error == null)
            {
                ViewBag.Message = "Produto salvo com sucesso!";
                ViewBag.Status = "OK";
            }
            else
            {
                ViewBag.Message = "Dados Inválidos. Tente novamente";
                ViewBag.Status = "FAIL";
            }

            ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoId", "Descricao");
            return View();
        }

        //GET: Vizualizar Produtos
        public ActionResult VisualizarProdutos()
        {
            var lista_produtos = db.Produto.ToList();
            lista_produtos.OrderBy(x => x.Nome);

            var model = new List<VisualizarProdutoVM>();
            foreach (var prod in lista_produtos)
            {
                var visualizador = new VisualizarProdutoVM()
                {
                    ProdutoID = prod.ProdutoID,
                    Nome = prod.Nome,
                    TipoAlimento = prod.TipoAlimento.Descricao,
                    UnidadeVenda = prod.Quantidade + " " + prod.UnidadeMedida,
                };

                model.Add(visualizador);
            }

            //Verificação se a Ação de deleção foi realizada para exibição de texto
            bool confirma_deleção = false;
            if (Session["Deleted"] != null)
                confirma_deleção = (bool)Session["Deleted"];

            if (confirma_deleção)
            {
                ViewBag.Deleted = true;
                Session["Deleted"] = false;
            }
            else
                ViewBag.Deleted = null;

            return View(model);
        }

        //GET: Cadastrar Opcional
        public ActionResult CadastrarOpcional()
        {
            ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoId", "Descricao");
            return View();
        }

        //POST: Cadastrar Opcional
        [HttpPost]
        public ActionResult CadastrarOpcional([Bind(Include = "Nome,TipoAlimentoID,Quantidade,UnidadeMedida,Valor,ImgFile")] OpcionalViewModel model)
        {
            if (ModelState.IsValid)
            {
                Opcional novo_opcional = new Opcional(model);
                byte[] imagem_binaria;

                if (model.ImgFile != null)
                {
                    try
                    {
                        Stream arquivoStream = model.ImgFile.InputStream;
                        imagem_binaria = new byte[arquivoStream.Length];
                        arquivoStream.Read(imagem_binaria, 0, imagem_binaria.Length);

                        if (imagem_binaria != null)
                        {
                            novo_opcional.Imagem = imagem_binaria;
                        }
                        else
                        {
                            ViewBag.Message = "Falha na leitura da imagem";
                            ViewBag.Status = "FAIL";
                            ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoId", "Descricao");
                            return View();
                        }

                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = " Erro " + ex.Message;
                        ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoId", "Descricao");
                        return View();
                    }
                }

                else
                {
                    novo_opcional.Imagem = null;
                }

                db.Opcional.Add(novo_opcional);
                db.SaveChanges();

            }
            else
            {
                ViewBag.Error = true;
            }

            if (ViewBag.Error == null)
            {
                ViewBag.Message = "Produto salvo com sucesso!";
                ViewBag.Status = "OK";
            }
            else
            {
                ViewBag.Message = "Dados Inválidos. Tente novamente";
                ViewBag.Status = "FAIL";
            }

            ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoId", "Descricao");
            return View();
        }

        //GET: Vizualizar Opcionais
        public ActionResult VisualizarOpcionais()
        {
            var lista_opcionais = db.Opcional.OrderBy(x => x.Nome).ToList();

            var model = new List<VisualizarOpcionalVM>();
            foreach (var prod in lista_opcionais)
            {
                VisualizarOpcionalVM visualizador = new VisualizarOpcionalVM()
                {
                    OpcionalID = prod.OpcionalID,
                    Nome = prod.Nome,
                    TipoAlimento = prod.TipoAlimento.Descricao,

EstrelaLivre/EstrelaLivre.Web/Controllers/CestaController.cs
using EstrelaLivre.Dados.Contexto;
using EstrelaLivre.Entidades.Modelos;
using EstrelaLivre.Entidades.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace EstrelaLivre.Web.Controllers
{
    public class CestaController : Controller
    {
        private ContextoDados db = new ContextoDados();

        //GET: Configurar Cestas
        public ActionResult ConfigurarCesta()
        {
            return View();
        }

        // GET: Disponibilizar Produtos
        public ActionResult DisponibilizarProdutos()
        {
            List<Produto> lista_produtos = db.Produto.OrderBy(p => p.Nome).ToList();

            ViewBag.Contador = (int)lista_produtos.Count();

            return View(lista_produtos);
        }

        // GET: Disponibilizar Opcionais
        public ActionResult DisponibilizarOpcionais()
        {
            List<Opcional> lista_opcionais = db.Opcional.OrderBy(p => p.Nome).ToList();

            ViewBag.Contador = (int)lista_opcionais.Count();

            return View(lista_opcionais);
        }

        //POST: Alterar Disponibilidade
        [HttpPost]
        public ActionResult AlterarDisponibilidade(int? id, string tipo)
        {
            if (tipo == "Produto")
            {
                var selecionado = db.Produto.Find(id);
                if (selecionado.Disponivel)
                {
                    selecionado.Disponivel = false;
                }
                else
                {
                    selecionado.Disponivel = true;
                }
                db.SaveChanges();

                return RedirectToAction("DisponibilizarProdutos");
            }
            else if (tipo == "Opcional")
            {
                var selecionado = db.Opcional.Find(id);
                if (selecionado.Disponivel)
                {
                    selecionado.Disponivel = false;
                }
                else
                {
                    selecionado.Disponivel = true;
                }
                db.SaveChanges();

                return RedirectToAction("DisponibilizarOpcionais");
            }

            return View();
        }

        //GET: Definir Quantidades
        public ActionResult DefinirQuantidades()
        {
            var definirVM = new DefinirViewModel();
            definirVM.lista_alimentos = db.TipoAlimento.Where(tpa => tpa.TipoAlimentoID <= 5).ToList();
            definirVM.quantidades = db.QuantidadesCB.Select(qtd => qtd.Quantidade).ToList();
            definirVM.ValorAtual = db.ValorCB.ToList().Last().ValorAtual;
            
            return View(definirVM);
        }

        //POST: Definir Quantidades e Valor Básico
        [HttpPost]
        public ActionResult DefinirQuantidades([Bind(Include = "lista_alimentos,quantidades,ValorAtual")] DefinirViewModel model)
        {
            model.lista_alimentos = db.TipoAlimento.Where(tpa => tpa.TipoAlimentoID <= 5).ToList();

            List<QuantidadesCB> lista_atualizada = new List<QuantidadesCB>();
            foreach (var alimento in model.lista_alimentos)
            {
                var linha_tabela = db.QuantidadesCB.Find(alimento.TipoAlimentoID);
                linha_tabela.Quantidade = model.quantidades[alimento.TipoAlimentoID - 1];
                lista_atualizada.Add(linha_tabela);
            }

            var valor_antigo = db.ValorCB.Where(x => x.DataTermino == null).First();
            valor_antigo.DataTermino = DateTime.Now;


            var valor_atualizado = new ValorCB();
            valor_atualizado.ValorAtual = model.ValorAtual;
            valor_atualizado.DataInicio = DateTime.Now;
            valor_atualizado.DataTermino = null;
            db.ValorCB.Add(valor_atualizado);

            db.SaveChanges();

            return RedirectToAction("ConfigurarCesta");
        }

        //Get: Nova Cesta
        public ActionResult NovaCesta()
        {
            int ultimo_id;
            CestaBasica ultima_cesta;
            /*
            try
            {
                ultima_cesta = db.CestaBasica.OrderByDescending(cb => cb.CestaBasicaID).First();
                ultimo_id = ultima_cesta.CestaBasicaID;
                Session["CestaBasicaID"] = ultima_cesta.CestaBasicaID;
            }
            catch (Exception e)
            {
                ultima_cesta = new CestaBasica()
                {
                    CestaBasicaID = 1,
                    UsuarioID = "1234",
                    ValorTotal = db.ValorCB.OrderByDescending(vcb => vcb.DataTermino).First().ValorAtual,
                    FormaPagamento = null,
                    Finalizada = false
                };
                db.CestaBasica.Add(ultima_cesta);
                db.SaveChanges();
                Session["CestaBasicaID"] = ultima_cesta.CestaBasicaID;
            }
            */
            var model = new NovaCestaViewModel();
            model.produtos = db.Produto.Where(p => p.Disponivel == true).ToList();
            model.opcionais = db.Opcional.Where(op => op.Disponivel == true).ToList();

            return View(model);
        }

        //POST: Adicionar Prodtuos ao Carrinho
        [HttpPost]
        public ActionResult AdicionarAoCarrinho(int id, string tipo)
        {
            int cestabasicaID = 1;
            bool relacaoexistente = false;

            if (tipo == "Produto")
            {
                RelacaoCestaProduto cestaproduto = db.CestaProduto.Find(cestabasicaID, id);

                if (cestaproduto == null)
                {
                    cestaproduto = new RelacaoCestaProduto()
                    {
                        CestabasicaID = cestabasicaID,
                        ProdutoID = id,
                        Quantidade = 1
                    };
                }
                else
                {
                    relacaoexistente = true;
                    cestaproduto.Quantidade += 1;
                }


                if (!relacaoexistente)
                    db.CestaProduto.Add(cestaproduto);
                db.SaveChanges();
            }

            if (tipo == "Opcional")
            {
                RelacaoCestaOpcional cestaopcional = db.CestaOpcional.Find(cestabasicaID, id);
                    
                if (cestaopcional == null)
                {
                    cestaopcional = new RelacaoCestaOpcional()
                    {
                        CestabasicaID = cestabasicaID,
                        OpcionalID = id,
                        Quantidade = 1,
                        ValorTotal = db.Opcional.Find(id).Valor
                    };
                }
                else
                {
                    relacaoexistente = true;
                    cestaopcional.Quantidade += 1;
                    cestaopcional.ValorTotal += db.Opcional.Find(id).Valor;
                }


                if (!relacaoexistente)
                    db.CestaOpcional.Add(cestaopcional);
                db.SaveChanges();
            }

            return RedirectToAction("NovaCesta");
        }
    }
}

EstrelaLivre/EstrelaLivre.Web/Views/Cesta/ConfigurarCesta.cshtml
@{
    ViewBag.Title = "Configurar";
}

<h2>Configurações de Cesta</h2>

<ul class="lista_configurar_cesta">
    <li><h3>@Html.ActionLink("Disponibilizar Produtos Básicos", "DisponibilizarProdutos", "Cesta", new { @class = "link_configurar" })</h3></li>
    <li><h3>@Html.ActionLink("Disponibilizar Produtos Opcionais", "DisponibilizarOpcionais", "Cesta", new { @class = "link_configurar" })</h3></li>
    <li><h3>@Html.ActionLink("Definir Quantidades e Valores", "DefinirQuantidades", "Cesta", new { @class = "link_configurar" })</h3></li>
</ul>

EstrelaLivre/EstrelaLivre.Web/Views/Cesta/DefinirQuantidades.cshtml
@model EstrelaLivre.Entidades.ViewModels.DefinirViewModel

@{
    ViewBag.Title = "Definir Quantidades";
}

<h2>Definir Quantidades e Valores</h2>
<br />
<h4>&nbsp;&nbsp;&nbsp;&nbsp; Informe aqui as novas quantidades e o novo valor base e CONFIRME ABAIXO.</h4>
<br />
<br />
@using (Html.BeginForm("DefinirQuantidades", "Cesta", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{   
    @Html.AntiForgeryToken()

    <div class="form-group" style="margin-left: 90px;">
        <div class="control-label col-md-2">
            @Html.DisplayTextFor(m => Model.lista_alimentos[0].Descricao)
        </div>
        <div class="col-md-10">
            @Html.TextBoxFor(m => Model.quantidades[0], htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.quantidades, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" style="margin-left: 90px;">
        <div class="control-label col-md-2">
            @Html.DisplayTextFor(m => Model.lista_alimentos[1].Descricao)
        </div>
        <div class="col-md-10">
            @Html.TextBoxFor(m => Model.quantidades[1], htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.quantidades, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" style="margin-left: 90px;">
        <div class="control-label col-md-2">
            @Html.DisplayTextFor(m => Model.lista_alimentos[2].Descricao)
        </div>
        <div class="col-md-10">
            @Html.TextBoxFor(m => Model.quantidades[2], htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.quantidades, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" style="margin-left: 90px;">
        <div class="control-label col-md-2">
            @Html.DisplayTextFor(m => Model.lista_alimentos[3].Descricao)
        </div>
        <div class="col-md-10">
            @Html.TextBoxFor(m => Model.quantidades[3], htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.quantidades, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" style="margin-left: 90px;">
        <div class="control-label col-md-2">
            @Html.DisplayTextFor(m => Model.lista_alimentos[4].Descricao)
        </div>
        <div class="col-md-10">
            @Html.TextBoxFor(m => Model.quantidades[4], htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.quantidades, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" style="margin-left: 90px;">
        <div class="control-label col-md-2">
            @Html.LabelFor(m => Model.ValorAtual)
        </div>
        <div class="col-md-10">
            @Html.TextBoxFor(m => Model.ValorAtual, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.ValorAtual, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" style="margin-left: 270px;">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Atualizar Valores" />
        </div>
    </div>
}

EstrelaLivre/EstrelaLivre.Web/Views/Cesta/DisponibilizarOpcionais.cshtml
@model IEnumerable<EstrelaLivre.Entidades.Modelos.Opcional>

@{
    ViewBag.Title = "DefinirCesta";
    int contador = Model.Count();
    int atualizador = 0;
}

<h2>Disponibilizar Produtos Opcionais</h2>
<br />
<h4>&nbsp;&nbsp;&nbsp;&nbsp; Escolha aqui quais opcionais devem estar disponíveis para aquisição</h4>
<br />
<br />
@while (contador > 0){
    @:<div class="row" style="align-content:center">
        foreach (var opcional in Model)
        {
            @:<div class="col-md-4" style="text-align:center;">
                @:<h3 style="text-align:center">@opcional.Nome</h3>
                if (opcional.Disponivel)
                { 
                    @:<h5 class="text-success">(Disponível!)</h5>
                }
                @:<img width=" 150" height="150" src="@Url.Action("getOpicImageById", "Admin", new { id = opcional.OpcionalID })" alt="Imagem do Produto" />
                @:<br /><br /><br />
                @:<div>
                    using(Html.BeginForm("AlterarDisponibilidade", "Cesta", FormMethod.Post))
                    {
                        @:<input type="hidden" value="@opcional.OpcionalID" name="id" id="id" />
                        @:<input type="hidden" value="Opcional" name="tipo" id="tipo" />
                        if (opcional.Disponivel) 
                        { 
                            @:<input type="submit" value="Esconder" class="btn btn-danger" />
                        }
                        else
                        {
                            @:<input type="submit" value="Disponibilizar" class="btn btn-success" />    
                        }
                    }
                @:</div>
            @:</div>
    
            contador -= 1;
            atualizador += 1;
            if (atualizador == 3){
                @:</div>
                @:<div class="row">
                @:<hr /> 
                atualizador = 0; 
            }
        }
    @:</div>
}

@Html.ActionLink("Retornar", "ConfigurarCesta", "Cesta")

EstrelaLivre/EstrelaLivre.Web/Views/Cesta/DisponibilizarProdutos.cshtml
@model IEnumerable<EstrelaLivre.Entidades.Modelos.Produto>

@{
    ViewBag.Title = "DefinirCesta";
    int contador = Model.Count();
    int atualizador = 0;
}

<h2>Disponibilizar Produtos Básicos</h2>
<br />
<h4>&nbsp;&nbsp;&nbsp;&nbsp; Escolha aqui quais produtos devem estar disponíveis para aquisição</h4>
<br />
<br />
@while (contador > 0){
    @:<div class="row" style="align-content:center">
        foreach (var produto in Model)
        {
            @:<div class="col-md-4" style="text-align:center;">
                @:<h3 style="text-align:center">@produto.Nome</h3>
                if (produto.Disponivel)
                { 
                    @:<h5 class="text-success">(Disponível!)</h5>
                }
                @:<img width=" 150" height="150" src="@Url.Action("getProdImageById", "Admin", new {id = produto.ProdutoID })" alt="Imagem do Produto" />
                @:<br /><br /><br />
                @:<div>
                    using(Html.BeginForm("AlterarDisponibilidade", "Cesta", FormMethod.Post))
                    {
                        @:<input type="hidden" value="@produto.ProdutoID" name="id" id="id" />
                        @:<input type="hidden" value="Produto" name="tipo" id="tipo" />
                        if (produto.Disponivel) 
                        { 
                            @:<input type="submit" value="Esconder" class="btn btn-danger" />
                        }
                        else
                        {
                            @:<input type="submit" value="Disponibilizar" class="btn btn-success" />    
                        }
                    }
                @:</div>
            @:</div>
    
            contador -= 1;
            atualizador += 1;
            if (atualizador == 3){
                @:</div>
                @:<div class="row">
                @:<hr /> 
                atualizador = 0; 
            }
        }
    @:</div>
}

@Html.ActionLink("Retornar", "ConfigurarCesta", "Cesta")

EstrelaLivre/EstrelaLivre.Web/Views/Cesta/NovaCesta.cshtml
@model EstrelaLivre.Entidades.ViewModels.NovaCestaViewModel

@{
    ViewBag.Title = "Nova Cesta";
    int idCesta = 1;
    int contador_produtos = Model.produtos.Count();
    int contador_opcionais = Model.opcionais.Count();
    int atualizador = 0;
}

<h2>Produtos Básicos<br /></h2>

@while (contador_produtos > 0)
{
    @:<div class="row" style="align-content:center">
        foreach (var produto in Model.produtos)
        {
            @:<div class="col-md-4" style="text-align:center;">
                @:<h3 style="text-align:center">@produto.Nome</h3>
                @:<img width=" 150" height="150" src="@Url.Action("getProdImageById", "Admin", new {id = produto.ProdutoID })" alt="Imagem do Produto" />
                @:<br /><br />
                @:<h4 style="text-align:center"><b>Tipo de Alimento: </b>@produto.TipoAlimento.Descricao</h4>
                @:<h4 style="text-align:center"><b>Quantidade: </b>@produto.Quantidade @produto.UnidadeMedida</h4>
                @:<div>
                    using (Html.BeginForm("AdicionarAoCarrinho", "Cesta", FormMethod.Post))
                    {
                        @:<input type="hidden" value="@produto.ProdutoID" name="id" id="id" />
                        @:<input type="hidden" value="Produto" name="tipo" id="tipo" />
                        @:<input type="submit" value="Adicionar ao Carrinho" class="btn btn-success" />
                    }
                    @:</div>
                @:</div>


                    contador_produtos -= 1;
                    atualizador += 1;
                    if (atualizador == 3)
                    {
                        @:</div>
                        @:<div class="row">
                        @:<hr />
                atualizador = 0;
                    }
        }
        @:</div>
}

<h2><br /><br />Produtos Opcionais<br /></h2>

@while (contador_opcionais > 0)
{
    @:<div class="row" style="align-content:center">
        foreach (var opcional in Model.opcionais)
        {
            @:<div class="col-md-4" style="text-align:center;">
                @:<h3 style="text-align:center">@opcional.Nome</h3>
                @:<img width=" 150" height="150" src="@Url.Action("getOpicImageById", "Admin", new { id = opcional.OpcionalID })" alt="Imagem do Produto" />
                @:<br /><br />
                @:<h4 style="text-align:center"><b>Quantidade: </b>@opcional.Quantidade @opcional.UnidadeMedida</h4>
                @:<h4 style="text-align:center"><b>Valor: </b>R$ @opcional.Valor</h4>
                @:<div>
                    using (Html.BeginForm("AdicionarAoCarrinho", "Cesta", FormMethod.Post))
                    {
                        @:<input type="hidden" value="@opcional.OpcionalID" name="id" id="id" />
                        @:<input type="hidden" value="Opcional" name="tipo" id="tipo" />
                        @:<input type="submit" value="Adicionar ao Carrinho" class="btn btn-success" />
                    }
                    @:</div>
                @:</div>


                    contador_opcionais -= 1;
                    atualizador += 1;
                    if (atualizador == 3)
                    {
                        @:</div>
                        @:<div class="row">
                        @:<hr />
                atualizador = 0;
                    }
        }
        @:</div>
}

<br /><br />
@using (Html.BeginForm("IrParaCarrinho", "Cesta", FormMethod.Get))
{
    @:<input type="submit" value="Finalizar Compra" class="btn btn-success" />
}