EstrelaLivre/EstrelaLivre.Web/Controllers/DeleteController.cs
using EstrelaLivre.Dados.Contexto;
using EstrelaLivre.Entidades.Modelos;
using EstrelaLivre.Entidades.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EstrelaLivre.Web.Controllers
{
    public class DeleteController : Controller
    {
        private ContextoDados db = new ContextoDados();

        // GET: Delete/Produto
        public ActionResult Produto(int id)
        {
            Produto deleteted_confirmed = db.Produto.Find(id);
            db.Produto.Remove(deleteted_confirmed);
            db.SaveChanges();

            Session["Deleted"] = true;
            return RedirectToAction("VisualizarProdutos", "Admin");
        }

        // GET: Delete/Opcional
        public ActionResult Opcional(int id)
        {
            Opcional deleteted_confirmed = db.Opcional.Find(id);
            db.Opcional.Remove(deleteted_confirmed);
            db.SaveChanges();

            Session["Deleted"] = true;
            return RedirectToAction("VisualizarOpcionais", "Admin");
        }

        // GET: Delete/Empresa
        public ActionResult Empresa(int id)
        {
            Empresa deleteted_confirmed = db.Empresa.Find(id);
            db.Empresa.Remove(deleteted_confirmed);
            db.SaveChanges();

            Session["Deleted"] = true;
            return RedirectToAction("VisualizarEmpresas", "Admin");
        }
    }
}

EstrelaLivre/EstrelaLivre.Web/Controllers/EditController.cs
using EstrelaLivre.Dados.Contexto;
using EstrelaLivre.Entidades.Modelos;
using EstrelaLivre.Entidades.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EstrelaLivre.Web.Controllers
{
    public class EditController : Controller
    {
        private ContextoDados db = new ContextoDados();

        // GET: Edit/Edit/ProdutoID
        public ActionResult Produto(int? id)
        {
            if (id != null)
            {
                Produto produto = db.Produto.Find(id);
                EditProdutoVM model = new EditProdutoVM(produto);

                ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoID", "Descricao", produto.TipoAlimentoID);
                return View(model);
            }

            return RedirectToAction("VisualizarProdutos", "Admin");
        }

        // POST: Edit/Edit/ProdutoID
        [HttpPost]
        public ActionResult Produto([Bind(Include="ProdutoID,Nome,TipoAlimentoID,Quantidade,UnidadeMedida,ImgFile")]EditProdutoVM produto_editado)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Produto corrigido = db.Produto.Find(produto_editado.ProdutoID);
                            corrigido.Nome = produto_editado.Nome;
                            corrigido.TipoAlimentoID = produto_editado.TipoAlimentoID;
                            corrigido.Quantidade = produto_editado.Quantidade;
                            corrigido.UnidadeMedida = produto_editado.UnidadeMedida;

                    byte[] imagem_binaria;

                    if (produto_editado.ImgFile != null)
                    {
                        try
                        {
                            Stream arquivoStream = produto_editado.ImgFile.InputStream;
                            imagem_binaria = new byte[arquivoStream.Length];
                            arquivoStream.Read(imagem_binaria, 0, imagem_binaria.Length);

                            if (imagem_binaria != null)
                            {
                                corrigido.Imagem = imagem_binaria;
                            }
                            else
                            {
                                ViewBag.Erro = "Falha na leitura da imagem";
                                ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoID", "Descricao", produto_editado.TipoAlimentoID);
                                return View();
                            }

                        }
                        catch (Exception ex)
                        {
                            ViewBag.Erro = " Erro " + ex.Message;
                            ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoID", "Descricao", produto_editado.TipoAlimentoID);
                            return View();
                        }
                    }

                    db.SaveChanges();
                    return RedirectToAction("VisualizarProdutos", "Admin");
                }

                ViewBag.Erro = "Favor Preencher todos os Campos Corretamente.";
                ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoID", "Descricao", produto_editado.TipoAlimentoID);
                return View();
            }
            catch(Exception e)
            {
                ViewBag.Erro = "Erro de conexão com o banco de dados. Contate seu Administrador.";
                ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoID", "Descricao", produto_editado.TipoAlimentoID);
                return View();
            }
        }

        // GET: Edit/Edit/OpcionalID
        public ActionResult Opcional(int? id)
        {
            if (id != null)
            {
                Opcional opcional = db.Opcional.Find(id);
                var model = new EditOpcionalVM(opcional);

                ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoID", "Descricao", opcional.TipoAlimentoID);
                return View(model);
            }

            return RedirectToAction("VisualizarOpcionais", "Admin");
        }

        // POST: Edit/Edit/OpcionalID
        [HttpPost]
        public ActionResult Opcional([Bind(Include = "OpcionalID,Nome,TipoAlimentoID,Quantidade,UnidadeMedida,Valor,ImgFile")]EditOpcionalVM opcional_editado)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Opcional corrigido = db.Opcional.Find(opcional_editado.OpcionalID);
                    corrigido.Nome = opcional_editado.Nome;
                    corrigido.TipoAlimentoID = opcional_editado.TipoAlimentoID;
                    corrigido.Quantidade = opcional_editado.Quantidade;
                    corrigido.UnidadeMedida = opcional_editado.UnidadeMedida;
                    corrigido.Valor = opcional_editado.Valor;

                    byte[] imagem_binaria;

                    if (opcional_editado.ImgFile != null)
                    {
                        try
                        {
                            Stream arquivoStream = opcional_editado.ImgFile.InputStream;
                            imagem_binaria = new byte[arquivoStream.Length];
                            arquivoStream.Read(imagem_binaria, 0, imagem_binaria.Length);

                            if (imagem_binaria != null)
                            {
                                corrigido.Imagem = imagem_binaria;
                            }
                            else
                            {
                                ViewBag.Erro = "Falha na leitura da imagem";
                                ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoID", "Descricao", opcional_editado.TipoAlimentoID);
                                return View();
                            }

                        }
                        catch (Exception ex)
                        {
                            ViewBag.Erro = " Erro " + ex.Message;
                            ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoID", "Descricao", opcional_editado.TipoAlimentoID);
                            return View();
                        }
                    }

                    db.SaveChanges();
                    return RedirectToAction("VisualizarOpcionais", "Admin");
                }

                ViewBag.Erro = "Favor Preencher todos os Campos Corretamente.";
                ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoID", "Descricao", opcional_editado.TipoAlimentoID);
                return View();
            }
            catch (Exception e)
            {
                ViewBag.Erro = "Erro de conexão com o banco de dados. Contate seu Administrador.";
                ViewBag.TipoAlimentoID = new SelectList(db.TipoAlimento, "TipoAlimentoID", "Descricao", opcional_editado.TipoAlimentoID);
                return View();
            }
        }

        // GET: Edit/Edit/EmpresaID
        public ActionResult Empresa(int? id)
        {
            if (id != null)
            {
                Empresa empresa = db.Empresa.Find(id);
                return View(empresa);
            }

            return RedirectToAction("VisualizarEmpresas", "Admin");
        }

        // POST: Edit/Edit/ProdutoID
        [HttpPost]
        public ActionResult Empresa(Empresa modificada)
        {
            if (ModelState.IsValid)
            {
                db.Entry(modificada).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("VisualizarEmpresas", "Admin");
            }
            ViewBag.Erro = "Favor Preencher os Campos Corretamente.";
            return View();
        }

    }
}

EstrelaLivre/EstrelaLivre.Web/Views/Admin/CadastrarEmpresa.cshtml
@model EstrelaLivre.Entidades.Modelos.Empresa

@{
    ViewBag.Title = "Cadastrar Empresa";
}

<h2>Nova Empresa</h2>

@if (ViewBag.Status == "OK")
{
    <h3 class="text-success">@ViewBag.Message</h3>
}
else if (ViewBag.Status == "FAIL")
{
    <h3 class="text-danger">@ViewBag.Message</h3>
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CNPJ, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CNPJ, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CNPJ, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logradouro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Logradouro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Logradouro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EstrelaLivre/EstrelaLivre.Web/Views/Admin/CadastrarOpcional.cshtml
@model EstrelaLivre.Entidades.ViewModels.OpcionalViewModel

@{
    ViewBag.Title = "Cadastrar Opcional";
}

<h2>Cadastrar Opcional</h2>

@if (ViewBag.Status == "OK")
{
    <h3 class="text-success">@ViewBag.Message</h3>
}
else if (ViewBag.Status == "FAIL")
{
    <h3 class="text-danger">@ViewBag.Message</h3>
}

@using (Html.BeginForm("CadastrarOpcional", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoAlimentoID, "TipoAlimentoID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoAlimentoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoAlimentoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnidadeMedida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnidadeMedida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnidadeMedida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Imagem do Produto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImgFile, new { type = "file" })
                @Html.ValidationMessageFor(model => model.ImgFile)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Rertornar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EstrelaLivre/EstrelaLivre.Web/Views/Admin/CadastrarProduto.cshtml
@model EstrelaLivre.Entidades.ViewModels.ProdutoViewModel

@{
    ViewBag.Title = "Cadastrar Produto";
}

<h2>Cadastrar Produto</h2>

@if (ViewBag.Status == "OK")
{
    <h3 class="text-success">@ViewBag.Message</h3>
}
else if (ViewBag.Status == "FAIL")
{
    <h3 class="text-danger">@ViewBag.Message</h3>
}

@using (Html.BeginForm("CadastrarProduto", "Admin", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoAlimentoID, "TipoAlimentoID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoAlimentoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoAlimentoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnidadeMedida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnidadeMedida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnidadeMedida, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.Label("Imagem do Produto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImgFile, new { type = "file" })
                @Html.ValidationMessageFor(model => model.ImgFile)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Rertornar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EstrelaLivre/EstrelaLivre.Web/Views/Admin/GerenciarAdministradores.cshtml
@model IEnumerable<EstrelaLivre.Entidades.ViewModels.RolesViewModel>
@{
    ViewBag.Title = "GerenciarAdministradores";
}

<h2>Gerenciar Permissões</h2>
<br />

<table class="table table-hover">
    <tr>
        <th style="font-size:20px;">
            Admnistradores
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        if (item.RoleName == "Administrador")
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @using (Html.BeginForm("GerenciarAdministradores", "Admin", FormMethod.Post))
                    {
                        <div class="form-group">
                            <input type="hidden" name="UserId" value="@item.UserID" />
                            <input type="hidden" name="UserRole" value="@item.RoleName" />
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Remover Privilégios" class="btn btn-default" />
                            </div>
                        </div>
                    }
                </td>
            </tr>
        }
    }
    <tr>
        <th style="font-size:20px;">
            Usuários
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        if (item.RoleName == "Usuario")
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @using (Html.BeginForm("GerenciarAdministradores", "Admin", FormMethod.Post))
                    {
                        <div class="form-group">
                            <input type="hidden" name="UserId" value="@item.UserID" />
                            <input type="hidden" name="UserRole" value="@item.RoleName" />
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Conceder Privilégios" class="btn btn-default" />
                            </div>
                        </div>
                    }
                </td>
            </tr>
        }
    }
</table>

EstrelaLivre/EstrelaLivre.Web/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Administrador";
}

<h2>Administrador</h2>

EstrelaLivre/EstrelaLivre.Web/Views/Admin/VisualizarEmpresas.cshtml
@model IEnumerable<EstrelaLivre.Entidades.ViewModels.EmpresaViewModel>

@{
    ViewBag.Title = "Visualizar Empresas";
}

<h2>Visualizar Empresas</h2>
<br />

@if (ViewBag.Deleted != null && ViewBag.Deleted)
{
    <h3 class="text-success">Empresa Deletada com Sucesso.</h3>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CNPJ)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Endereco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cidade)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CNPJ)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Endereco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cidade)
        </td>
        <td>
            @Html.ActionLink("Editar", "Empresa", "Edit", new { id = item.EmpresaID }, new { id = item.EmpresaID }) |
            @Html.ActionLink("Deletar", "Empresa", "Delete", new { id = item.EmpresaID }, new { id = item.EmpresaID })
        </td>
    </tr>
}

</table>

EstrelaLivre/EstrelaLivre.Web/Views/Admin/VisualizarOpcionais.cshtml
@model IEnumerable<EstrelaLivre.Entidades.ViewModels.VisualizarOpcionalVM>

@{
    ViewBag.Title = "Visualizar Opcionais";
}

<h2>Visualizar Opcionais</h2>
<br />

@if (ViewBag.Deleted != null && ViewBag.Deleted)
{
    <h3 class="text-success">Produto Deletado com Sucesso.</h3>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoAlimento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnidadeVenda)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrecoVenda)
        </th>
        <th>
            @Html.DisplayName("Imagem")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoAlimento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnidadeVenda)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecoVenda)
            </td>
            <td>
                <img width="75" height="75" src="@Url.Action("getOpicImageById", "Admin", new {id = item.OpcionalID })" alt="Imagem do Produto" />
            </td>
            <td>
                @Html.ActionLink("Editar", "Opcional", "Edit", new { id = item.OpcionalID }, new { id = item.OpcionalID }) |
                @Html.ActionLink("Deletar", "Opcional", "Delete", new { id = item.OpcionalID }, new { id = item.OpcionalID })
            </td>
        </tr>
    }

</table>

EstrelaLivre/EstrelaLivre.Web/Views/Admin/VisualizarProdutos.cshtml
@model IEnumerable<EstrelaLivre.Entidades.ViewModels.VisualizarProdutoVM>

@{
    ViewBag.Title = "Visualizar Produtos";
}

<h2>Visualizar Produtos</h2>
<br />

@if (ViewBag.Deleted != null && ViewBag.Deleted)
{
    <h3 class="text-success">Produto Deletado com Sucesso.</h3>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoAlimento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnidadeVenda)
        </th>
        <th>
            @Html.DisplayName("Imagem")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoAlimento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnidadeVenda)
        </td>
        <td>
            <img width="75" height="75" src="@Url.Action("getProdImageById", "Admin", new {id = item.ProdutoID })" alt="Imagem do Produto" />
        </td>
        <td>
            @Html.ActionLink("Editar", "Produto", "Edit", new { id = item.ProdutoID }, new { id = item.ProdutoID }) |
            @Html.ActionLink("Deletar", "Produto", "Delete", new { id = item.ProdutoID }, new { id = item.ProdutoID })
        </td>
    </tr>
}

</table>